### ISSUE TITLE
Board Games List

### ISSUE THREAD

**Issue by kabaskill** [itsmyrice/gamedalf#3]
### Value Proposition

**As a** user
**I want to** see a list of board games
**that** I'd like to play with my friends.

### Description

![List Of  #Games]()

### Acceptance Criteria

- [ ] A title is displayed at the top of the screen reading “Gamedalf”
- [ ] The display is optimised for mobile view
- [ ] The layout should be vertical
- [ ] The first 10 games from the API are displayed in a list of game cards
- [ ] Every game should show the cover, name, rating and genre (if it has, player count)
- [ ] If there is an issue loading the movie data from the source, an error message is displayed to the user

### Tasks

- [ ] Create the feature branch `game-lists`
- [ ] Install xml-js with `npm install xml-js`
- [ ] Fetch the XML data from the API 
- [ ] Convert the data to JSON
- [ ] Create the `GameCard` component
- [ ] `GameCard` props: `cover`, `name`, `rating`, `genre`
- [ ] Create a `GameList` component and render 10 games
- [ ] `GameList` props: `data`
- [ ] Map through the fetched list of data and render a `GameCard` component for each game

---

**Comment by F-Kirchhoff** [comment]
This is already a very good user story. I would suggest not to create a GameList component yet, since at this moment in time it just adds a layer of complexity without adding any real value (reusability or reduction of complexity) to the project. But you can keep in mind that you can refactor this code into a List component later on when you want to render a second list of game cards (at which point it will have the benefit of reusing the code!).
