### ISSUE TITLE
2: Game Details Page

### ISSUE THREAD

**Issue by kkenjeres** [itsmyrice/gamedalf#4]
## Value proposition

As a user I want to be able to read the details/information of the game so that I can easily decide which game to play

## Description

![Image](https://github.com/itsmyrice/gamedalf/assets/85419045/62d14e99-5497-4b39-859d-079ab0258c51)

## Acceptance criteria

- [ ] The user selects a game from the list on the homepage and it will directed to the details page of that selected game
 - [ ] The game's cover, name, rating, genre, age range and player range will be displayed.
 - [ ] The description or information about the game will be displayed.
 - [ ] The user can go back to the homepage by clicking the ⬅️ button on the bottom of the details page

## Tasks

- [ ] Create the feature branch game-details-page
- [ ]  Create the file pages/games/[id].js for game details page
-[ ] Render the game's cover, name, rating, genre, age range, player range and description in [id].js
-[ ] import Link from next/Link
-[ ] Add the Links in [id].js and details page
