### ISSUE TITLE
Create Navbar

### ISSUE THREAD

**Issue by kkenjeres** [itsmyrice/gamedalf#5]
## Value proposition

As a user 
I want to see navigation bar on the page
In order to navigate by some link

## Acceptance criteria

- [ ] Create Header.js component 
- [ ] Use semantic tags as <nav> during creating layout
- [ ] We need have Home / Search / Profile pages at the moment
- [ ] We need have Home / Search / Profile pages at the moment

## Tasks

- [ ] Create Header.js component 
- [ ] Use semantic tags as <nav> during creating layout
- [ ] We need have Home / Search / Profile pages at the moment
- [ ] Import Header to the every page on App.js  and put it before <main> 
- [ ] Import Link from next/link and set <Link> to the links
